import NavBar from "@/components/NavBar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "@/components/Header";

const poppins = Poppins({ weight: ["400", "500", "600"], subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<main className="bg-gray-100 min-h-screen w-screen">
					<main className="max-w-screen-2xl m-auto bg-white">
						<NavBar />
						<Header />

						{children}
					</main>
				</main>
			</body>
		</html>
	);
}
